<?php echo $this->partial('page-title', array(
	'title' => $this->model->name,
	'model' => $this->model,
	'crud'	=> $this->crud,
)); ?>

<dl class="dl-inline">
	<dt>
		Published By
	</dt>
	<dd>
		<a href="#">Publisher goes here</a>
	</dd>
</dl>

<nav class="navbar navbar-default">
	<ul class="nav navbar-nav">
		<li class="active"><a href="#">Info</a></li>
	</ul>
	<div class="collapse navbar-collapse">
		<ul class="nav navbar-nav">
			<li><a href="#">Forums <span class="badge">17</span></a></li>
			<li><a href="#">Trading <span class="badge">1</span></a></li>
			<li><a href="#">Lists <span class="badge">5</span></a></li>
			<li><a href="#">Files</a></li>
			<li><a href="#">Ratings &amp; Reviews</a></li>
		</ul>
		<ul class="nav navbar-nav navbar-right">
			<li class="dropdown">
				<a class="dropdown-toggle" data-toggle="dropdown" href="#">Not watched <span class="caret"></span></a>
				<ul class="dropdown-menu" role="menu">
					<li><a href="#"><span class="glyphicon glyphicon-eye-open"></span> Watch page for changes</a></li>
					<li><a href="#"><span class="glyphicon glyphicon-time"></span> View page history</a></li>
				</ul>
			</li>
			<li class="dropdown">
				<a class="dropdown-toggle" data-toggle="dropdown" href="#">Not owned <span class="caret"></span></a>
				<ul class="dropdown-menu" role="menu">
					<li><a href="#"><span class="glyphicon glyphicon-star"></span> Add to wishlist</a></li>
					<li><a href="#"><span class="glyphicon glyphicon-ok"></span> Mark as owned</a></li>
				</ul>
			</li>
		</ul>
	</div>
</nav>

<div class="row">
	<div class="col-md-4">
		<div class="images">
			<div class="row">
				<div class="col-md-12">
					<img class="img-responsive img-thumbnail" src="/img/pathfinder/box.jpg">
				</div>
			</div>
			<div class="row">
				<div class="col-md-6">
					<img class="img-responsive img-thumbnail" src="/img/pathfinder/1.jpg">
				</div>
				<div class="col-md-6">
					<div class="img-container">
						<a class="img-control img-thumbup" href="#"><span class="glyphicon glyphicon-thumbs-up"> 11</span></a>
						<a class="img-control img-report" href="#" title="Report this image"><span class="text-danger glyphicon glyphicon-warning-sign"></</span></a>
						<img class="img-responsive img-thumbnail" src="/img/pathfinder/2.jpg">
					</div>
				</div>
			</div>
			<p class="text-center"><a href="#">More images</a></p>
		</div> <!-- images -->
		
		<div class="feed">
			<ul class="media-list">
				<li class="media">
					<a class="pull-left">
						<img class="media-object" src="http://localhost:8888/img/pathfinder/1.jpg" height="64px" alt="">
					</a>
					<div class="media-body">
						<h4 class="media-heading">Forums: <a href="#">Game boxes improved with googly eyes</a></h4>
						<p>This is my effort:</p>
					</div>
				</li>
				<li class="media">
					<a class="pull-left">
						<img class="media-object" src="http://localhost:8888/img/pathfinder/1.jpg" height="64px" alt="">
					</a>
					<div class="media-body">
						<h4 class="media-heading">Forums: <a href="#">Why Paizo must listen to me!!!</a></h4>
						<p>I have a degree in boardgameology from...</p>
					</div>
				</li>
				<li class="media">
					<a class="pull-left">
						<img class="media-object" src="http://localhost:8888/img/pathfinder/1.jpg" height="64px" alt="">
					</a>
					<div class="media-body">
						<h4 class="media-heading">Trading: <a href="#">Custom PACG Inserts</a></h4>
						<p>Since the accident, I've a lot of free time, so I decided to spend it crafting these exquisite...</p>
					</div>
				</li>
				<li class="media">
					<a class="pull-left">
						<img class="media-object" src="http://localhost:8888/img/pathfinder/1.jpg" height="64px" alt="">
					</a>
					<div class="media-body">
						<h4 class="media-heading">Lists: <a href="#">The Best Card Games of 2013</a></h4>
						<p>
							24th<br>
							by <a href="#">Eddard Stark</a>
						</p>
					</div>
				</li>
			</ul>
			<p class="text-center"><a href="#">More Popular Content</a></p>
		</div>
	</div> <!-- left col -->
	<div class="col-md-8">
		<div class="well description">
			<?php echo $this->escapehtml('Description goes here'); ?>
		</div> <!-- description -->
		<div class="info text-center">
			<div class="row">
				<div class="col-md-4 players">
					<h4>Number of Players</h4>
					<div class="row">
						<span class="glyphicon glyphicon-user"></span>
						<span class="glyphicon glyphicon-user"></span>
						<span class="glyphicon glyphicon-user"></span>
						<span class="glyphicon glyphicon-user"></span>
					</div>
					1 - 4
				</div>
				<div class="col-md-4 suggested-ages">
					<h4>Suggested Age</h4>
					<div class="years">
						<span class="age">13+</span>
					</div>
					13 years old and up
				</div>
				<div class="col-md-4 playing-time">
					<h4>Playing Time</h4>
					<div class="row">
						<div class="stopwatch">
							<div class="tick"></div>
							<div class="tick"></div>
							<div class="tick"></div>
							<div class="tick"></div>
							<div class="tick"></div>
							<div class="tick"></div>
							<div class="tick"></div>
							<div class="tick"></div>
							<div class="tick"></div>
							<div class="tick"></div>
							<div class="tick"></div>
							<div class="tick"></div>
							<span class="length">90</span>
						</div>
					</div>
					90 minutes
				</div>
			</div>
		</div> <!-- info -->
		<div class="properties">
			<h4>Properties</h4>
			<dl class="dl-horizontal">
				<dt>Themes</dt>
				<dd>
					<ul class="list-inline">
						<li><a href="#">Fantasy</a></li>
						<li><a href="#">Exploration</a></li>
						<li><a href="#">Combat</a></li>
					</ul>
				</dd>
				<dt>Mechanics</dt>
				<dd>
					<ul class="list-inline">
						<li><a href="#">Co-operative Play</a></li>
						<li><a href="#">Deck Building</a></li>
						<li><a href="#">Dice Rolling</a></li>
					</ul>
				</dd>
			</dl>
		</div> <!-- properties -->
		<div class="components">
			<h4>Components</h4>
			<ul>
				<li>500 Cards</li>
				<li>5 Polyhedral Dice</li>
			</ul>
		</div> <!-- components -->
		<div class="expansions">
			<h4>Expansions</h4>
			<ul>
				<li><a href="#">Pathfinder Adventure Card Game: Rise of the Runelords - Character Add-On Deck</a></li>
				<li><a href="#">Pathfinder Adventure Card Game: Rise of the Runelords - The Skinsaw Murders Adventure Deck</a></li>
				<li><a href="#">Pathfinder Adventure Card Game: Rise of the Runelords - The Hook Mountain Massacre Adventure Deck</a></li>
			</ul>
		</div> <!-- expansions -->
	</div> <!-- right col -->
</div>
