Home

<div class="row">
	<div class="col-md-3 col-sm-6">
		<div class="card red">
			<div class="card-title">
				A story about my life
			</div>
			<div class="card-image">
				<img class="img-responsive" src="https://en.gravatar.com/userimage/8153754/c29caad30cb5a1b413b36a777765e427.png?size=250">
			</div>
			<div class="card-subtitle">
				Forums - revlob
			</div>
			<div class="card-summary">
				So there I was, standing in this room, when all of a sudden...
				<div class="card-score">15</div>
			</div>
		</div>
	</div>
	<div class="col-md-3 col-sm-6">
		<div class="card red">
			<div class="card-title">
				Pathfinder Adventure Card Game: Rise of the Runelords - Base Set 
			</div>
			<div class="card-image">
				<img class="img-responsive" src="/img/pathfinder/1.jpg">
			</div>
			<div class="card-subtitle">
				Images - revlob
			</div>
			<div class="card-summary">
				So there I was, standing in this room, when all of a sudden...
				<div class="card-score">15</div>
			</div>
		</div>
	</div>
	<div class="col-md-3 col-sm-6">
		<div class="card red">
			<div class="card-title">
				A story about my life
			</div>
			<div class="card-image">
				<img class="img-responsive" src="https://en.gravatar.com/userimage/8153754/c29caad30cb5a1b413b36a777765e427.png?size=250">
			</div>
			<div class="card-subtitle">
				Forums - revlob
			</div>
			<div class="card-summary">
				So there I was, standing in this room, when all of a sudden...
				<div class="card-score">15</div>
			</div>
		</div>
	</div>
	<div class="col-md-3 col-sm-6">
		<div class="card red">
			<div class="card-title">
				Pathfinder Adventure Card Game: Rise of the Runelords - Base Set 
			</div>
			<div class="card-image">
				<img class="img-responsive" src="/img/pathfinder/2.jpg">
			</div>
			<div class="card-subtitle">
				Forums - revlob
			</div>
			<div class="card-summary">
				So there I was, standing in this room, when all of a sudden...
				<div class="card-score">15</div>
			</div>
		</div>
	</div>
</div>