<div class="row">
	<div class="col-md-6">
		<?php echo $this->partial('page-title', array(
			'title'		=> 'Groups',
			'paginator'	=> $this->paginator,
			'crud'		=> $this->crud,
		)); ?>
		<?php echo $this->tabulate($this->paginator); ?>
	</div>
	<div class="col-md-6">
		<?php echo $this->partial('page-title', array(
			'title'		=> 'Events',
		)); ?>
		<?php echo $this->tabulate($this->paginator); ?>
	</div>
</div>
