<?php echo $this->partial('page-title', array(
	'title'		=> $this->model->name,
	'crud'		=> $this->crud,
)); ?>

<?php echo $this->partial('info/authorship', array('model' => $this->model)); ?>

<div class="row">
	<div class="col-md-6">
		<?php echo $this->partial('page-title', array(
			'title'		=> 'Members',
			'paginator'	=> $this->members,
		)); ?>
		<?php echo $this->tabulate($this->members); ?>
	</div>
	<div class="col-md-6">
		<?php echo $this->partial('page-title', array(
			'title'		=> 'Events',
		)); ?>
		<?php echo $this->tabulate($this->events); ?>
	</div>
</div>
