<ul class="crud list-inline">
	<?php foreach ($this->actions as $action => $icon): ?>
	<?php
		$routeParams = array('action' => $action);
		if ($this->model) {
			$routeParams['key'] = $this->model->key;
		}
	?>
	<li><a class="btn btn-default" href="<?php echo $this->url(null, $routeParams); ?>"><span class="glyphicon glyphicon-<?php echo $icon; ?>"></span> <?php echo $this->translate(ucwords($action)); ?></a></li>
	<?php endforeach; ?>
</ul>