<?php

use Zend\Paginator\Paginator;

$paginator = $this->paginator;
$currentItemStart = (($paginator->getCurrentPageNumber() - 1) * $paginator->getItemCountPerPage()) + 1;
$currentItemEnd = $currentItemStart + $paginator->getCurrentItemCount() - 1;
$totalItemCount = $paginator->getTotalItemCount();

$pages = $paginator->getPages();

?>
<ul class="pagination">
	<?php if (isset($pages->previous)): ?>
	<li><a href="<?php echo $this->url(null, array(), array('query'=>array('page'=>$pages->previous)), true); ?>"><span class="glyphicon glyphicon-chevron-left"></span></a></li>
	<?php else: ?>
	<li class="disabled"><a href="#"><span class="glyphicon glyphicon-chevron-left"></span></a></li>
	<?php endif; ?>
	<li><a href=""><?php echo $currentItemStart?> - <?php echo $currentItemEnd; ?> of <?php echo $totalItemCount; ?></a></li>
	<?php if (isset($pages->next)): ?>
	<li><a href="<?php echo $this->url(null, array(), array('query'=>array('page'=>$paginator->getPages()->next)), true); ?>"><span class="glyphicon glyphicon-chevron-right"></span></a></li>
	<?php else: ?>
	<li class="disabled"><a href="#"><span class="glyphicon glyphicon-chevron-right"></span></a></li>
	<?php endif; ?>
</ul>