<?php echo $this->doctype(); ?>

<!-- Default layout -->
<html lang="en">
	<?php echo $this->partial('html-head'); ?>
	<body>
		<nav class="navbar navbar-static-top navbar-inverse" role="navigation">
			<div class="navbar-header">
				<a class="navbar-brand" href="/"><?php echo $this->translate('Flatland'); ?></a>
			</div>
		</nav>
		
		<div class="container">
			<?php echo $this->partial('flash-messenger'); ?>
			
			<div class="row">
				<div class="col-md-6 col-md-offset-3">
					<div class="paper">
						<?php echo $this->content; ?>
					</div>
				</div>
			</div>
			
		</div> <!-- /container -->
		
		<?php echo $this->partial('navigation-bottom'); ?>
		
		
		<?php echo $this->partial('html-body-end'); ?>
		
		
	</body>
</html>
