<td>
	<?php if ($this->options['primary_action']): ?>
	<a class="btn" href="<?php echo $this->url(null, array('action' => $this->options['primary_action'], 'key' => $this->data->key)); ?>"><?php echo $this->escapehtml($this->data->fullName); ?></a>
	<?php else: ?>
	<?php echo $this->prettyText($this->data->name); ?>
	<?php endif; ?>
</td>
<td>
	<?php echo $this->prettyTime($this->data->created); ?>
</td>