<?php $element = $this->element; ?>
<label class="col-lg-<?php echo $this->leftColWidth; ?> control-label" for="<?php echo $element->getAttribute('id'); ?>"><?php echo $element->getLabel(); ?></label>
<div class="col-lg-<?php echo $this->rightColWidth; ?>">
	<?php echo $this->formElement($element); ?>
	<?php if ($this->formElementErrors($element)): ?>
	<span class="help-block"><?php echo $this->formElementErrors($element); ?></span>
	<?php endif; ?>
</div>
<script type="text/javascript">
	$(function () {
		$(document).ready(function () {
			console.log('Attaching autocompleter');
			$('#<?php echo $element->getAttribute('id')?>').autocomplete({
				source: <?php echo json_encode($this->url($element->getSource(), $element->getSourceOptions())); ?>,
				response: function(event, ui) {
					var items = ui.content[0].items;
					ui.content.pop();
					if (items.length === 0) {
						ui.content.push({label: 'No Results', value: ''});
					}
					$.each(items, function(n, i) {
						ui.content.push({label: i.name, value: i.key});
					});
				}
			});
		});
	});
</script>