<label class="col-lg-<?php echo $this->leftColWidth; ?> control-label" for="<?php echo $element->getAttribute('id'); ?>"><?php echo $element->getLabel(); ?></label>
<div class="col-lg-<?php echo $this->rightColWidth; ?>">
	<?php if ($element->getEscapeHtml()): ?>
	<p class="form-control-static"><?php echo $this->escapehtml($element->getValue()); ?></p>
	<?php else: ?>
	<p class="form-control-static"><?php echo $element->getValue(); ?></p>
	<?php endif; ?>
</div>