<nav class="navbar navbar-default">
	<?php echo $this->navigation($this->nav)->menu()->setPartial('nav/navbar'); ?>
	<ul class="nav navbar-nav navbar-right">
		<li class="dropdown">
			<a class="dropdown-toggle" data-toggle="dropdown" href="#">Not watched <span class="caret"></span></a>
			<ul class="dropdown-menu" role="menu">
				<li><a href="#"><span class="glyphicon glyphicon-eye-open"></span> Watch page for changes</a></li>
				<li><a href="#"><span class="glyphicon glyphicon-time"></span> View page history</a></li>
			</ul>
		</li>
		<li class="dropdown">
			<a class="dropdown-toggle" data-toggle="dropdown" href="#">Not owned <span class="caret"></span></a>
			<ul class="dropdown-menu" role="menu">
				<li><a href="#"><span class="glyphicon glyphicon-star"></span> Add to wishlist</a></li>
				<li><a href="#"><span class="glyphicon glyphicon-ok"></span> Mark as owned</a></li>
			</ul>
		</li>
	</ul>
</nav>