<?php

$element->setAttribute('class', 'form-control');
$elementType = $element->getAttribute('type');
if (!$elementType) {
	throw new \Exception('Missing element type for: ' . get_class($element));
}

?>
<div class="form-group<?php if ($this->formElementErrors($element)) echo " has-error"; ?>">
	<?php echo $this->partial(
			'partial/form/element-friendly/' . $elementType . '.phtml',
			array(
				'element'		=> $element,
			)); ?>
</div>