<div class="form-group">
	<fieldset class="<?php echo $unwrap ? "col-lg-offset-$leftColWidth col-lg-$rightColWidth" : ''; ?>">
		<?php foreach ($fieldset as $element): ?>
		<?php echo $this->partial(
				'partial/form/element-horizontal.phtml',
				array(
					'element'		=> $element,
					'leftColWidth'	=> 2,
					'rightColWidth'	=> 4,
					'unwrap'		=> $unwrap,
				)); ?>
		<?php endforeach; ?>
	</fieldset>
</div>