<?php

use Zend\Form\Fieldset;

$fieldset = $this->fieldset;
//$form->prepare();

?>
<?php foreach ($fieldset as $element): ?>
<?php if ($element instanceof Fieldset): ?>
<?php echo $this->partial(
		'partial/form/sub-fieldset.phtml',
		array('fieldset' => $element)); ?>
<?php else: ?>
<?php echo $this->partial(
		'partial/form/element-horizontal.phtml',
		array(
			'element'		=> $element,
			'leftColWidth'	=> 2,
			'rightColWidth'	=> 4,
		)); ?>
<?php endif; ?>
<?php endforeach; ?>
