<?php

$form = $this->form;
$form->setAttributes(array(
	'action'	=> $this->url(null, array(), array(), true),
	'class'		=> $form->getAttribute('name') . ' form-inline',
	'role'		=> 'form',
));
$form->prepare();
echo $this->form()->openTag($form);

?>
<?php foreach ($form as $element): ?>
<?php echo $this->partial(
		'partial/form/element-inline.phtml',
		array(
			'element'		=> $element,
		)); ?>
		
<?php endforeach; ?>
<?php echo $this->form()->closeTag($form); ?>
