<?php echo $this->doctype(); ?>

<!-- Default layout -->
<html lang="en">
	<head>
		<?php
			echo $this->headTitle($this->translate('Flatland'))
				->setSeparator(' - ')
				->setAutoEscape(false);
		?>
			
	    	
		<!-- Meta -->
		<?php
			echo $this->headMeta()
				->setCharset('utf-8')
				->appendName('viewport', 'width=device-width, initial-scale=1.0');
		?>
			
	
		<!-- Styles and links -->
		<?php
			echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/favicon.ico'))
				->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
				->prependStylesheet($this->basePath() . '/css/flatland.css');
		?>
			
	
		<!-- Head Scripts -->
		<?php
			echo $this->headScript()
				->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
				->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',));
		?>
			
	
	</head>
    <body>
        <nav class="navbar navbar-static-top navbar-inverse" role="navigation">
        	<div class="navbar-header">
        		<a class="navbar-brand" href="/"><?php echo $this->translate('Flatland'); ?></a>
        	</div>
        	
        	<ul class="nav navbar-nav navbar-right">
        		<li>
        			<a href="#"><span class="badge">2</span> Messages</a>
        		</li>
        		<li class="dropdown">
        			<a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-user"></span> Jon Snow <span class="caret"></span></a>
        			<ul class="dropdown-menu" role="menu">
        				<li>
        					<a href="#">User Preferences</a>
        				</li>
        				<li>
        					<a href="#">Sign Out</a>
        				</li>
        			</ul>
        		</li>
        	</ul>
        </nav>
        <div class="container">
        
            <?php echo $this->content; ?>
            
            <footer>
            	<p>Here's some footer stuff</p>
            </footer>
        </div> <!-- /container -->
        
        <!-- End of body scripts -->
        <?php
        	echo $this->inlineScript()
	        	->prependFile($this->basePath() . '/js/bootstrap.min.js')
	        	->prependFile($this->basePath() . '/js/jquery.min.js');
        ?>
        
        
    </body>
</html>
