<?php echo $this->doctype(); ?>

<!-- Default layout -->
<html lang="en">
	<head>
		<?php
			echo $this->headTitle($this->translate('Flatland'))
				->setSeparator(' - ')
				->setAutoEscape(false);
		?>
			
	    	
		<!-- Meta -->
		<?php
			echo $this->headMeta()
				->setCharset('utf-8')
				->appendName('viewport', 'width=device-width, initial-scale=1.0');
		?>
			
	
		<!-- Styles and links -->
		<?php
			echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/favicon.ico'));
			//echo $this->headLink()->prependStylesheet($this->basePath() . '/css/compileLess.php');
			echo $this->headLink()->prependStylesheet($this->basePath() . '/css/flatland.css');
		?>
			
	
		<!-- Head Scripts -->
		<?php
			echo $this->headScript()
				->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
				->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',));
		?>
			
	
	</head>
	<body>
		<?php if ($this->authService()->hasIdentity()): ?>
		<nav class="navbar navbar-static-top admin" role="navigation">
			<div class="navbar-header">
				<a class="navbar-brand" href="/"><?php echo $this->translate('Admin'); ?></a>
			</div>
			<ul class="nav navbar-nav">
				<li>
					<a href="<?php echo $this->url('admin/database'); ?>"><span class="glyphicon glyphicon-book"></span> <?php echo $this->translate('Database'); ?></a>
				</li>
				<li>
					<a href="<?php echo $this->url('admin/users'); ?>"><span class="glyphicon glyphicon-user"></span> Users</a>
				</li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li>
					<a href="#"><span class="badge">3</span> Reports</a>
				</li>
				<li>
					<a href="#"><span class="badge">9</span> Queue</a>
				</li>
			</ul>
		</nav>
		<?php endif; ?>
		<nav class="navbar navbar-static-top navbar-inverse" role="navigation">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-top-collapse">
					<span class="glyphicon glyphicon-align-justify"></span>
				</button>
				<a class="navbar-brand" href="/"><?php echo $this->translate('Flatland'); ?></a>
			</div>
			
			<div class="collapse navbar-collapse navbar-top-collapse">
				<ul class="nav navbar-nav">
					<li class="active">
						<a href="<?php echo $this->url('games'); ?>"><span class="glyphicon glyphicon-tower"></span> Games</a>
					</li>
					<li>
						<a href="#"><span class="glyphicon glyphicon-comment"></span> Forums</a>
					</li>
					<li>
						<a href="#"><span class="glyphicon glyphicon-shopping-cart"></span> Trading</a>
					</li>
					<li>
						<a href="#"><span class="glyphicon glyphicon-calendar"></span> Groups &amp; Events</a>
					</li>
					<li>
						<a href="#"><span class="glyphicon glyphicon-list"></span> Lists</a>
					</li>
				</ul>
				<?php if ($this->authService()->hasIdentity()): ?>
				<ul class="nav navbar-nav navbar-right">
					<li>
						<a href="#"><span class="badge">17</span> Updates</a>
					</li>
					<li>
						<a href="#"><span class="badge">2</span> Messages</a>
					</li>
					<li>
						<?php if ($this->authService()->getIdentity()->isPasswordAuthenticated()): ?>
						<a href="#" title="<?php echo $this->translate('This session has been password-authenticated'); ?>"><span class="glyphicon glyphicon-lock text-success"></span></a>
						<?php else: ?>
						<a href="#" title="<?php echo $this->translate('This session has not been password-authenticated'); ?>"><span class="glyphicon glyphicon-lock text-warning"></span></a>
						<?php endif; ?>
					</li>
					<li class="dropdown">
						<a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-user"></span> <?php echo $this->escapehtml($this->authService()->getIdentity()->fullName); ?> <span class="caret"></span></a>
						<ul class="dropdown-menu" role="menu">
							<li>
								<a href="<?php echo $this->url('user'); ?>"><?php echo $this->translate('User Preferences'); ?></a>
							</li>
							<li>
								<a href="<?php echo $this->url('logout'); ?>"><?php echo $this->translate('Sign out'); ?></a>
							</li>
						</ul>
					</li>
				</ul>
				<?php else: ?>
				<div class="navbar-right">
					<a class="btn btn-warning navbar-btn" href="<?php echo $this->url('signup'); ?>"><?php echo $this->translate('Create an account'); ?></a>
					<a class="btn btn-primary navbar-btn" href="<?php echo $this->url('login'); ?>"><?php echo $this->translate('Sign in'); ?></a>
				</div>
				<?php endif; ?>
			</div>
		</nav>
		<div class="container">
			<?php echo $this->partial('flash-messenger'); ?>
			
			<?php echo $this->content; ?>
			
			<hr>
			<footer>
				<ul class="list-inline">
					<li>
						<a href="#"><?php echo $this->translate('About'); ?></a>
					</li>
					<li>
						<a href="#"><?php echo $this->translate('Privacy'); ?></a>
					</li>
					<li>
						<a href="#"><?php echo $this->translate('Terms'); ?></a>
					</li>
					<li>
						&copy; <a href="">omelett.es Ltd</a> <?php echo date('Y'); ?>
					</li>
				</ul>
			</footer>
		</div> <!-- /container -->
		
		<!-- Body end scripts -->
		<?php
			echo $this->inlineScript()
				->prependFile($this->basePath() . '/js/bootstrap.min.js')
				->prependFile($this->basePath() . '/js/jquery.min.js');
		?>
		
		
	</body>
</html>
