<?php echo $this->doctype(); ?>

<!-- Default layout -->
<html lang="en">
	<head>
		<?php
			echo $this->headTitle($this->translate('Flatland'))
				->setSeparator(' - ')
				->setAutoEscape(false);
		?>
			
	    	
		<!-- Meta -->
		<?php
			echo $this->headMeta()
				->setCharset('utf-8')
				->appendName('viewport', 'width=device-width, initial-scale=1.0');
		?>
			
	
		<!-- Styles and links -->
		<?php
			echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/favicon.ico'));
			echo $this->headLink()->prependStylesheet($this->basePath() . '/css/jquery-ui/jquery-ui.min.css')
				->prependStylesheet($this->basePath() . '/css/compileLess.php');
				//->prependStylesheet($this->basePath() . '/css/flatland.css');
		?>
			
	
		<!-- Head Scripts -->
		<?php
			echo $this->headScript()
				->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
				->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
				->appendFile('//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js')
				->appendFile('//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js')
				->appendFile($this->basePath() . '/js/flatland.js');
		?>
			
	
	</head>
	<body>
		<?php $aclRole = $this->authService()->hasIdentity() ? $this->authService()->getIdentity()->aclRole : 'guest'; ?>
		<?php if ($this->aclService()->isAllowed($aclRole, 'admin')): ?>
		<nav class="navbar navbar-static-top navbar-default admin" role="navigation">
			<div class="navbar-header">
				<a class="navbar-brand" href="/"><?php echo $this->translate('Admin'); ?></a>
			</div>
			<?php echo $this->navigation('admin_navigation')->menu()->setUlClass('nav navbar-nav')->setPartial('nav/navbar'); ?>
		</nav>
		<?php endif; ?>
		<nav class="navbar navbar-static-top navbar-inverse" role="navigation">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-top-collapse">
					<span class="glyphicon glyphicon-align-justify"></span>
				</button>
				<a class="navbar-brand" href="/"><?php echo $this->translate('Flatland'); ?></a>
			</div>
			
			<div class="collapse navbar-collapse navbar-top-collapse">
				<?php echo $this->navigation('navigation')->menu()->setUlClass('nav navbar-nav')->setPartial('nav/navbar'); ?>
				<?php if ($this->authService()->hasIdentity()): ?>
				<ul class="nav navbar-nav navbar-right">
					<li>
						<?php if ($this->authService()->getIdentity()->isPasswordAuthenticated()): ?>
						<a href="#" title="<?php echo $this->translate('This session has been password-authenticated'); ?>"><span class="glyphicon glyphicon-lock text-success"></span></a>
						<?php else: ?>
						<a href="#" title="<?php echo $this->translate('This session has not been password-authenticated'); ?>"><span class="glyphicon glyphicon-lock text-warning"></span></a>
						<?php endif; ?>
					</li>
					<li class="dropdown">
						<a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="badge">31</span> <?php echo $this->translate('Notifications'); ?> <span class="caret"></span></a>
						<ul class="dropdown-menu role="menu">
							<li>
								<a href="#"><span class="badge">2</span> Messages</a>
							</li>
							<li>
								<a href="#"><span class="badge">17</span> Game Updates</a>
							</li>
							<?php if ($this->aclService()->isAllowed($aclRole, 'admin')): ?>
							<li role="presentation" class="divider"></li>
							<li role="presentation" class="dropdown-header">Admin</li>
							<li>
								<a href="#"><span class="badge">3</span> Reports</a>
							</li>
							<li>
								<a href="#"><span class="badge">9</span> Queue</a>
							</li>
							<?php endif; ?>
						</ul>
					</li>
					<li class="dropdown">
						<a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-user"></span> <?php echo $this->escapehtml($this->authService()->getIdentity()->fullName); ?> <span class="caret"></span></a>
						<ul class="dropdown-menu" role="menu">
							<li>
								<a href="<?php echo $this->url('user'); ?>"><?php echo $this->translate('User Preferences'); ?></a>
							</li>
							<li>
								<a href="<?php echo $this->url('logout'); ?>"><?php echo $this->translate('Sign out'); ?></a>
							</li>
						</ul>
					</li>
				</ul>
				<?php else: ?>
				<div class="navbar-right">
					<a class="btn btn-warning navbar-btn" href="<?php echo $this->url('signup'); ?>"><?php echo $this->translate('Create an account'); ?></a>
					<a class="btn btn-primary navbar-btn" href="<?php echo $this->url('login'); ?>"><?php echo $this->translate('Sign in'); ?></a>
				</div>
				<?php endif; ?>
			</div>
		</nav>
		<div class="container">
			<?php echo $this->partial('flash-messenger'); ?>
			
			<?php echo $this->content; ?>
			
			<hr>
			<footer>
				<div class="pull-right">
					<span class="text-muted glyphicon glyphicon-info-sign"></span>
				</div>
				<ul class="list-inline">
					<li>
						<a href="#"><?php echo $this->translate('About'); ?></a>
					</li>
					<li>
						<a href="#"><?php echo $this->translate('Privacy'); ?></a>
					</li>
					<li>
						<a href="#"><?php echo $this->translate('Terms'); ?></a>
					</li>
					<li>
						&copy; <a href="">omelett.es Ltd</a> <?php echo date('Y'); ?>
					</li>
				</ul>
			</footer>
		</div> <!-- /container -->
		
		<!-- Body end scripts -->
		<?php
			echo $this->inlineScript()
				->appendFile($this->basePath() . '/js/bootstrap.min.js');
		?>
		
		
	</body>
</html>
